### ISSUE TITLE
Option to invert orbit controls in gcode viewer

### ISSUE THREAD

**Issue by turpinator** [cncgoko/Goko#29]
Not sure if youre continuing dev, see the last commit was ~4 months ago, but might as well suggest nonetheless.  Oh. I see the dev branch has an update a few days ago.  Good to see.

Add an option to invert the orbit controls in the gcode viewer, as it stands, it is completely inverse of every single program with ant sort of 3D view that Ive ever seen.

Anyway, this looks awesome, Id love to see it completed/I dont know.  I just know I dont care for Chilipeppr.

Err... I dont know how to add labels.  I barely use github as it is.  My bad. :)

**Comment by cncgoko** [comment]
@turpinator Hello

The dev is still going on :) mainly on the dev branch and the next release is planned anytime soon. And it's pretty cool to see some requests here. I gives me motivation for the devs.

Your request is a good idea, I'm used to inverted mouse (in CAD, games...).
Just to be clear, when you wirte "an option to invert the orbit controls", what does that mean ?
- Invert the used mouse button ? (left click = orbit, and right click = move)
or
- Invert the response of the orbit to the mouse moves ? 

Can you please give more detail about the expected behavior of the camera given the mouse motion ?

Thanks,
Psyko

**Comment by turpinator** [comment]
Invert the response.  So it will be like this.  http://i.imgur.com/lKLLhEw.gifv  Mouse goes right, object rotates counterclockwise (from above).   Hard to explain, I guess.

As for the mouse buttons, i guess it is a little reversed than what im used to, but thats easier to relearn than the orbit directions.

**Comment by cncgoko** [comment]
I see. This should not be a problem.

**Comment by cncgoko** [comment]
Preferences panel is available in latest release (0.3.1)

**Comment by turpinator** [comment]
Had a chance to try it today, exactly what I was thinking. :+1:

**Comment by cncgoko** [comment]
@turpinator 
Thanks for the feedback :)
